spring.application.name=ResumeAI

server.port=${PORT:8080}

# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d8dgnkbbc2fs73ek4950-a:5432/resumeai_db_35ha
spring.datasource.username=resumeai_db_35ha_user
spring.datasource.password=UXKTh5XjAX10gqhtyapypdisYN8mReXV
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=your-secret-key
app.jwt.expiration=86400000

# OpenAI
openai.api.key=your-openai-key
openai.api.url=https://api.openai.com/v1
openai.model=gpt-4o-mini
